### ISSUE TITLE
Is this really needed after vim implemented floating windows?

### ISSUE THREAD

**Issue by poetaman** [gillyb/stable-windows#10]
Is this really needed after vim implemented popups? I guess one could open a floating window and display whatever in that? 

@lacygoill any input? am not a vim expert :)

**Comment by gillyb** [comment]
Yes, it's not really related to floating windows, because it still happens with the quickfix window and some other times when working with various splits.

That being said, I'm not using this myself, since it doesn't work perfectly and don't currently have the time to maintain it. I think I will migrate it to lua sometime soon, and hopefully get back to using it.

**Comment by luukvbaal** [comment]
@gillyb I went ahead and created a lua plugin that tries to solve the same problem as this does: [stabilize.nvim](https://github.com/luukvbaal/stabilize.nvim)

I think it also fixes some of the issues people were experiencing i.e. #2 #3 #6 #7 #8 #9, not sure about the rest.

**Comment by gillyb** [comment]
Very Cool!
Thanks a lot @luukvbaal !!

I'll add a note in the readme to check your plugin out instead, since i'm not planning on maintaining this one.
